name: ci

on:
  push:
    branches:
      - main
    
jobs:
  push_to_registry:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.2

      - name: Test
        working-directory: ./src
        run: go test -v ./...

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
 
      - name: Create SHA Substring
        uses: bhowell2/github-substring-action@v1.0.0
        id: sha
        with:
          value: ${{ github.sha }}
          length_from_start: 7
          
      - name: Build Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: minghsu0107/cicd-demo-ga:${{ github.ref_name }}-${{ steps.sha.outputs.substring }},minghsu0107/cicd-demo-ga:latest

      - name: Update Manifests
        uses: minghsu0107/update-kustomization@v1.0.5
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          IMAGES: minghsu0107/cicd-demo-ga
          IMAGE_TAG: ${{ github.ref_name }}-${{ steps.sha.outputs.substring }}
          MANIFEST_HOST: github.com
          MANIFEST_USER: minghsu0107
          MANIFEST_REPO: cicd-demo-ga-manifests
          MANIFEST_BRANCH: main
          KUSTOMIZATION: production